/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Score } from "./score";
import { Expose, Type } from "class-transformer";

export class Classification extends SpeakeasyBase {
  /**
   * Name of the "configuration",  a collection of SenseML queries for extracting document data.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "configuration" })
  configuration?: string;

  /**
   * The number of fingerprints defined in this config.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "fingerprints" })
  fingerprints?: number;

  /**
   * The number of this config's fingerprints that Sensible found in the document.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "fingerprints_present" })
  fingerprintsPresent?: number;

  /**
   * The score for the extraction, used to help choose the best extraction.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "score" })
  @Type(() => Score)
  score?: Score;
}
