/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Score } from "./score";
import { Expose, Type } from "class-transformer";

export class ClassificationPortfolio extends SpeakeasyBase {
  /**
   * Name of the "configuration",  a collection of SenseML queries for extracting document data.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "configuration" })
  configuration?: string;

  /**
   * The score for the extraction, used to help choose the best extraction.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "score" })
  @Type(() => Score)
  score?: Score;
}
