/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Content type of the document being presented for extraction. This field is optional, but if supplied must be presented consistently in all interactions.
 */
export enum ContentTypeEnum {
  ApplicationPdf = "application/pdf",
  ImageJpeg = "image/jpeg",
  ImagePng = "image/png",
  ImageTiff = "image/tiff",
}
