/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Extraction status (WAITING, COMPLETE, FAILED)
 */
export enum ExtractionStatusEnum {
  Waiting = "WAITING",
  Complete = "COMPLETE",
  Failed = "FAILED",
}
