/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExtractionStatusEnum } from "./extractionstatusenum";
import { Expose, Transform } from "class-transformer";

/**
 * Returns the ID to use to retrieve the extraction.
 */
export class ExtractFromUrlPortfolioResponse extends SpeakeasyBase {
  /**
   * Date and time Sensible created the extraction
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  created?: Date;

  /**
   * Unique ID for the extraction, used to retrieve the extraction
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Extraction status (WAITING, COMPLETE, FAILED)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: ExtractionStatusEnum;

  /**
   * Specifies the document types contained in the PDF portfolio.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "types" })
  types?: string[];
}
