/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Extraction status (WAITING, COMPLETE, FAILED)
 */
export enum ExtractionStatus {
    Waiting = "WAITING",
    Complete = "COMPLETE",
    Failed = "FAILED",
}
