/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Extraction status (WAITING, COMPLETE, FAILED)
 */
export enum ExtractionStatusEnum {
  Waiting = "WAITING",
  Complete = "COMPLETE",
  Failed = "FAILED",
}
