/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ClassificationPortfolio } from "./classificationportfolio";
import { FileMetadata } from "./filemetadata";
import { Validation } from "./validation";
import { ValidationsSummary } from "./validationssummary";
import { Expose, Type } from "class-transformer";

export class ExtractionContentPortfolio extends SpeakeasyBase {
  /**
   * Metadata about how Sensible chose the config to use for this extraction. The summary doesn't return fingerprints information for portfolio extractions.
   */
  @SpeakeasyMetadata({ elemType: ClassificationPortfolio })
  @Expose({ name: "classification_summary" })
  @Type(() => ClassificationPortfolio)
  classificationSummary?: ClassificationPortfolio[];

  /**
   * Name of the "configuration",  a collection of SenseML queries for extracting document data.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "configuration" })
  configuration?: string;

  /**
   * Extraction error messages.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "errors" })
  errors?: string[];

  /**
   * Metadata about the PDF file, for example author, authoring tool, and modified date.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "file_metadata" })
  @Type(() => FileMetadata)
  fileMetadata?: FileMetadata;

  /**
   * Data extracted from the document, structured as an array of fields.
   *
   * @remarks
   * Configure the verbosity parameter in the SenseML configuration to return
   * extraction metadata, such as:
   * - page numbers
   * - the bounding polygons that
   * define line coordinates
   * - for text that Sensible OCR'd, confidence scores.
   * For more information, see [Verbosity](doc:verbosity).
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "parsed_document" })
  parsedDocument?: Record<string, any>;

  /**
   * Summary of the extracted fields that failed validation rules you write in the Sensible app.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "validation_summary" })
  @Type(() => ValidationsSummary)
  validationSummary?: ValidationsSummary;

  /**
   * Which extracted fields failed validation rules you write in the Sensible app
   */
  @SpeakeasyMetadata({ elemType: Validation })
  @Expose({ name: "validations" })
  @Type(() => Validation)
  validations?: Validation[];
}
