/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Data extracted from the document, structured as an array of fields.
 *
 * @remarks
 * Configure the verbosity parameter in the SenseML configuration to return
 * extraction metadata, such as:
 * - page numbers
 * - the bounding polygons that
 * define line coordinates
 * - for text that Sensible OCR'd, confidence scores.
 * For more information, see [Verbosity](doc:verbosity).
 *
 */
export class ParsedDocument extends SpeakeasyBase {}
