/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Summary of the extracted fields that failed validation rules you write in the Sensible app.
 */
export class ValidationsSummary extends SpeakeasyBase {
    /**
     * Number of validation errors in the extraction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    errors?: number;

    /**
     * Number of fields specified in the SenseML config to extract from the document
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fields" })
    fields?: number;

    /**
     * Actual number of non-null fields extracted from the document
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fields_present" })
    fieldsPresent?: number;

    /**
     * Number of fields skipped in the extraction because a prerequisite field was null
     */
    @SpeakeasyMetadata()
    @Expose({ name: "skipped" })
    skipped?: number;

    /**
     * Number of validation warnings in the extraction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "warnings" })
    warnings?: number;
}
