/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetCsvExtractionRequest extends SpeakeasyBase {
  /**
   * Comma-delimited list of unique extraction IDs.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=ids" })
  ids: string;
}

/**
 * Indicates the extraction successfully converted to an CSV file. This response contains the download URL for the CSV file. The link
 *
 * @remarks
 * expires after 15 minutes.
 *
 */
export class GetCsvExtraction200ApplicationJSON extends SpeakeasyBase {
  /**
   * The download URL for the CSV file
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}

export class GetCsvExtractionResponse extends SpeakeasyBase {
  /**
   * Bad Request
   */
  @SpeakeasyMetadata()
  badRequest?: string;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Internal Server Error
   */
  @SpeakeasyMetadata()
  sensibleEncounteredAnUnknownError?: string;

  /**
   * Not authorized
   */
  @SpeakeasyMetadata()
  unauthorized?: string;

  /**
   * Unsupported Media Type
   */
  @SpeakeasyMetadata()
  unsupportedMediaType?: string;

  /**
   * Indicates the extraction successfully converted to an CSV file. This response contains the download URL for the CSV file. The link
   *
   * @remarks
   * expires after 15 minutes.
   *
   */
  @SpeakeasyMetadata()
  getCsvExtraction200ApplicationJSONObject?: GetCsvExtraction200ApplicationJSON;
}
