/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetExcelExtractionRequest extends SpeakeasyBase {
  /**
   * Comma-delimited list of unique extraction IDs.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=ids" })
  ids: string;
}

export class GetExcelExtractionResponse extends SpeakeasyBase {
  /**
   * Bad Request
   */
  @SpeakeasyMetadata()
  badRequest?: string;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Internal Server Error
   */
  @SpeakeasyMetadata()
  sensibleEncounteredAnUnknownError?: string;

  /**
   * Not authorized
   */
  @SpeakeasyMetadata()
  unauthorized?: string;

  /**
   * Unsupported Media Type
   */
  @SpeakeasyMetadata()
  unsupportedMediaType?: string;

  /**
   * Indicates the extraction successfully converted to an Excel file. This response contains the download URL for the Excel file. The link
   *
   * @remarks
   * expires after 15 minutes.
   *
   */
  @SpeakeasyMetadata()
  getExcelExtraction200ApplicationJSONAny?: any;
}
