/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetExcelExtractionRequest extends SpeakeasyBase {
    /**
     * Comma-delimited list of unique extraction IDs.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=ids" })
    ids: string;
}

/**
 * Indicates the extraction successfully converted to an Excel file. This response contains the download URL for the Excel file. The link
 *
 * @remarks
 * expires after 15 minutes.
 *
 */
export class GetExcelExtractionResponseBody extends SpeakeasyBase {
    /**
     * The download URL for the Excel file
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url?: string;
}

export class GetExcelExtractionResponse extends SpeakeasyBase {
    /**
     * Bad Request
     */
    @SpeakeasyMetadata()
    badRequest?: string;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Internal Server Error
     */
    @SpeakeasyMetadata()
    sensibleEncounteredAnUnknownError?: string;

    /**
     * Not authorized
     */
    @SpeakeasyMetadata()
    unauthorized?: string;

    /**
     * Unsupported Media Type
     */
    @SpeakeasyMetadata()
    unsupportedMediaType?: string;

    /**
     * Indicates the extraction successfully converted to an Excel file. This response contains the download URL for the Excel file. The link
     *
     * @remarks
     * expires after 15 minutes.
     *
     */
    @SpeakeasyMetadata()
    object?: GetExcelExtractionResponseBody;
}
