name: Generate

permissions:
  checks: write
  pull-requests: write
  contents: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14 # Import the sdk generation workflow which will handle the generation of the SDKs and publishing to the package managers
    with:
      force: ${{ github.event.inputs.force }}
      speakeasy_version: latest
      openapi_docs: |
        - ./sensible.yml
      languages: |-
        - typescript
      publish_typescript: true
      mode: pr
      create_release: true
    secrets:
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}

